### ISSUE TITLE
Botのステータスがonlineから変わらない

### ISSUE THREAD

**Issue by naoido** [naoido/neko-bot#6]
↓dadで設定しているが、onlineになっている
<img width="249" alt="image" src="https://github.com/user-attachments/assets/b04c0196-0f17-4049-b0d0-dbf43e81385e">

**Comment by AnnkoATAMA** [comment]
@naoido 
これ
https://pkg.go.dev/github.com/bwmarrin/discordgo#Status
dndのタイポでは....

**Comment by naoido** [comment]
@AnnkoATAMA 
おっしゃる通りです....
